spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: gsilva11
    url: jdbc:mysql://localhost:3306/quitanda?createDatabaseIfNotExist=true
    username: gusto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8090
quitanda:
  jwt:
    expiration: 86400000
    secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN}x3?JR3.2zr~v)gYF^8:8>:XfB:Ww75N/emt9Yj[bQMNCWwWJ?N,nvH.<2.r~w]e~vgak)X"v8HMH/7"2E,^k@n<vE-wD3g9JWPy;CrY.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb98FH^b[X3jzVER&:jw2<=c38=>L/zBq}C6tT*cCSVC^c]-L}&/