spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/quitanda
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true